# Generated by Django 4.2.1 on 2023-05-24 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_first_name', models.CharField(blank=True, max_length=55, verbose_name='Contractor First Name')),
                ('contractor_last_name', models.CharField(blank=True, max_length=55, verbose_name='Contractor Last Name')),
                ('contractor_company', models.CharField(blank=True, max_length=55, verbose_name='Contractor Company')),
                ('contractor_phone', models.CharField(blank=True, max_length=11, verbose_name='Contractor Phone')),
                ('contractor_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contractor Email')),
                ('contractor_address', models.CharField(blank=True, max_length=55, verbose_name='Contractor Address')),
                ('contractor_city', models.CharField(blank=True, max_length=55, verbose_name='Contractor City')),
                ('contractor_state', models.CharField(blank=True, max_length=55, verbose_name='Contractor State')),
                ('contractor_zip', models.CharField(blank=True, max_length=9, verbose_name='Contractor Zip Code')),
                ('contractor_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=55, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=55, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Phone Number')),
                ('alt_phone', models.CharField(blank=True, max_length=10, verbose_name='Alt Phone Number')),
                ('company', models.CharField(blank=True, max_length=55, verbose_name='Company')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=55, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=55, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=55, verbose_name='State')),
                ('zip', models.CharField(blank=True, max_length=9, verbose_name='Zip Code')),
                ('customer_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date_created', models.DateTimeField(default=datetime.datetime(2023, 5, 24, 12, 46, 57, 530856))),
                ('payment_type', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card')], max_length=25, verbose_name='Payment Method')),
                ('payment_status', models.CharField(blank=True, choices=[('BALANCE', 'Balance'), ('PAID', 'Paid'), ('CREDIT', 'Credit')], max_length=25, verbose_name='Payment Status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Sales Tax')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Total')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Deposit')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Balance')),
                ('invoice_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.contractor')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_unit', models.CharField(default='ea', max_length=255)),
                ('product_vendor', models.CharField(blank=True, max_length=255)),
                ('product_is_delete', models.BooleanField(default=False)),
                ('product_material', models.CharField(blank=True, choices=[('NATURAL QUARTZITE', 'Natural Quartzite'), ('ENGINEERED QUARTZ', 'Engineered Quartz'), ('GRANITE', 'Granite'), ('MARBLE', 'Marble'), ('DOLOMITE', 'Dolomite'), ('SOAPSTONE', 'Soapstone'), ('OTHER', 'Other')], max_length=255)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('product_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.product')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invoice.invoice')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.product')),
            ],
        ),
    ]
